module.exports = {
    verbose: true,
    debug: true,
    coverage: true,
    threshold: 90,
    lint: true,
    assert: 'code',
    'coverage-path': 'lib',
    'coverage-exclude': 'config',
    //paths: ['test'],
    paths: ['test/manager.js',
            'test/controllers/login.js',
            'test/plugins/api.js',
            'test/plugins/auth.js',
            'test/plugins/assets.js',
            'test/plugins/docs.js',
            'test/plugins/db.js',
            'test/plugins/redirect.js',
            'test/plugins/errors.js',
            'test/plugins/routes.js'],
    globals: '__core-js_shared__' // https://github.com/tgriesser/knex/issues/1720
};
